# Generated by Django 5.1.7 on 2025-03-26 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
