# Generated by Django 5.1.7 on 2025-03-29 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_readinglist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadingList',
        ),
    ]
