# Generated by Django 5.1.7 on 2025-04-02 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_readinglistbook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readinglistbook',
            options={},
        ),
    ]
